name: CI with Flyway & Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install ansible requests docker mysql-connector-python

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install community.mysql
          ansible-galaxy collection install community.docker

      - name: Bring environment up (MySQL + Flyway migrations)
        run: ansible-playbook ansible/up.yml -e "ansible_python_interpreter=/usr/bin/python3"

      - name: Run CRUD tests
        env:
          DB_HOST: 127.0.0.1
          DB_USER: sub_user
          DB_PASSWORD: sub_pass
          DB_NAME: subscriptions
        run: |
          sleep 5
          pytest -v tests/test_subscribers.py

      - name: Tear down environment
        if: always()
        run: ansible-playbook ansible/down.yml -e "ansible_python_interpreter=/usr/bin/python3"

      - name: Print completion message
        run: echo "CI pipeline completed for commit ${{ github.sha }}"
